name: Build Artifacts

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: call the other repo
        env:
          GITHUB_TOKEN: ${{ secrets.CROSS_REPO_SECRET }}
        run: |
          curl -d "{\"event_type\": \"xxx\"}" -H "Content-Type: application/json" -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/ferranbt/testrepo2/dispatches"
